---
title: "Vastcat"
author: "Hannah Chang"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
#set up
setwd("C:/Users/hanna/OneDrive - London School of Hygiene and Tropical Medicine/2_STEPH/DAE")
install.packages("foreign")
install.packages("epiDisplay")
library(foreign)
library(ggplot2)
library(epiDisplay)
library(tidyverse)

list.of.packages <- c("gt", "gtsummary", "tidyverse")
{
  new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
  if(length(new.packages)) install.packages(new.packages)
  lapply(list.of.packages, require, character.only = TRUE)
}

#import dta
vastcat <- read.dta("vastcat.dta")
str(vastcat)
head(vastcat)

```

## 

```{r datacleaning}
# recode values
vastcat$agegp <- factor(vastcat$agegp, levels=c(1:5), labels=c("0-11","12-23", "24-35", "36-47", "48-59"))
vastcat$sex <- factor(vastcat$sex, levels=c(1,2), labels=c("Male", "Female"))
vastcat$anaemia <- factor(vastcat$anaemia, levels=c(0,1), labels=c("normal", "anaemia"))
vastcat$wazcat <- factor(vastcat$wazcat, levels=c("normal", "underwt"), labels=c("normal", "underweight"))
vastcat$bcgscar <- factor(vastcat$bcgscar, levels=c(0,1), labels=c("absent", "present"))
vastcat$measles <- factor(vastcat$measles, levels=c(0,1), labels=c("no", "yes"))
vastcat$admitted <- factor(vastcat$admitted, levels=c(0,1), labels=c("no", "yes"))
vastcat$currbf <- factor(vastcat$currbf, levels=c(0,1), labels=c("no", "yes"))
vastcat$motheduc <- factor(vastcat$motheduc, levels=c(0,1), labels=c("no", "yes"))
vastcat$handpump <- factor(vastcat$handpump, levels=c(1:3), labels=c("yes", "not currently functioning", "no"))
vastcat$vita <- factor(vastcat$vit, levels=c(0,1), labels=c("normal", "deficient"))


```


```{r q1a}
# table 1
age_by_sex <- vastcat %>%
  select(sex, agegp) %>%
  tbl_summary(by=sex,
              label=agegp ~ 'Age Group (months)') %>%
  modify_header(label ~ "") %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Sex**") %>%
  add_overall(col_label="**Total**", last=TRUE) %>%
  modify_caption("**Table 1. Characteristics of Chidren by Age and Sex**") %>%
  bold_labels() 

age_by_sex

age_by_sex_2 <- vastcat %>%
    tbl_cross(
      row = agegp,
      col = sex,
      percent = "cell", 
      label=list(
        agegp~'Age group (months)',
        sex~'Sex')
    ) %>%
  add_stat_label() %>% 
  modify_caption("**Table 1. Characteristics of Chidren by Age and Sex**")%>%
  as_gt(include=-tab_footnote)
  )

age_by_sex_2

#need to add footnotes
```

```{r q1b}
nutrition <- vastcat %>%
  select(wazcat, hazcat, whzcat, anaemia, vita) %>%
  tbl_summary(
    label= c(
      wazcat ~ 'Weight for age', 
      hazcat ~ 'Height for age', 
      whzcat ~ 'Weight for height',
      anaemia ~ 'Haemoglobin level (g/dl)', 
      vita ~ 'Serum retinol level (mmol/l)'
    )
  )%>%
  modify_caption("**Table 2. Characteristics of Children by Nutritional Status**") %>%
  bold_labels() %>%
  as_gt(include = -tab_footnote) %>%
  tab_footnote(
    footnote = md("A child was classified as 'underweight' when the weight-for-age Z-score <-2"),
    locations = cells_body(rows=3)
  ) %>%
  tab_footnote(
    footnote = md("A child was classified as 'stunted' when the height-for-age Z-score <-2"),
    locations = cells_body(rows=6)
  ) %>%
  tab_footnote(
     footnote = md("A child was classified as 'wasted' when the weight-for-height Z-score <-2"),
     locations = cells_body(rows=9)
    ) %>%
  tab_footnote(
    footnote = md("A child was classified as 'anaemia' if the haemoglobin level<8 g/dl"),
    locations = cells_body(rows=12)
  ) %>%
  tab_footnote(
    footnote = md("A child was classified as 'deficient' if the serum retinol level<0.7 mmol/l"),
    locations = cells_body(rows=15)
  ) %>%
   opt_footnote_marks(marks = "numbers")

nutrition


```

```{r q1c}
#table
other <- vastcat %>%
  select(bcgscar, measles, admitted, currbf, motheduc) %>%
  tbl_summary(
    type = c(
      measles ~ "categorical",
      admitted ~ "categorical",
      currbf ~ "categorical",
      motheduc ~ "categorical"),
    label= c(
      bcgscar ~ 'BCG vaccination scar', 
      measles ~ 'Measles history', 
      admitted ~ 'Hospital admission during past year',
      currbf ~ 'Currently breasfed', 
      motheduc ~ 'Education status of mother'
    )
  )%>%
  modify_caption("**Table 3. Characteristics of Children by Other Risk Factors**") %>%
  bold_labels() 

other

```

